<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" exclude-result-prefixes="msxsl" xmlns:user="urn:my-scripts">
    <xsl:output method="xml" indent="yes"/>
   
    <xsl:template match="@* | node()">
      <Html>
        <head>
          <style type="text/css">
            .main table{
            border: 1px solid black;
            }
            .main th{
            border: 1px solid black;
            }
            .main td{
            border: 1px solid black;
            text-align: center;
            }
          </style>
        </head>
        <Body>
          <div class="header">
            <table>
              <tr>
                <td>
                  <image href="logoImage" alt="Logo Inage"/>
                </td>
                <td>
                  <div class="menu">
                    <ul>
                      <li>
                        <a href="viewList">View list</a>
                      </li>
                      <li>
                        <a href="viewList">View <xsl:call-template name="itemType"/></a>
                      </li>
                      <li>
                        <a href="viewList">Manage My allerts</a>
                      </li>
                      <li>
                        <a href="viewList">Feedback</a>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            </table>
          </div>
          <div class="main">
            <p>Hello {DUser.LoginName}</p>
            <p>Announcmenting you about events on the server</p>
            <p>
              User <a href="/_layouts/userdisp.aspx?ID={SUser.ID}">{SUser.LoginName}</a> <xsl:call-template name="itemType"/> <a href="viewItem">item</a>
            </p>
            <p>The following fields of <xsl:call-template name="itemType"/> was modified</p>
            <table class="table">
              <tr>
                <th>FieldName</th>
                <th>Previous Value</th>
                <th>Next Value</th>
              </tr>
              <xsl:for-each select="./EventData[1]/Field[(@Changed = 'true') and (string-length(./@DisplayName) &gt; 0)]">
                    <tr>
                      <th><xsl:value-of select="@DisplayName"/></th>
                      <th><xsl:value-of select="@Old"/></th>
                      <th><xsl:value-of select="@New"/></th>
                    </tr>
              </xsl:for-each>
            </table>

            <p>Other fields of <xsl:call-template name="itemType"/>: </p>
            <table class="table">
              <tr>
                <th>FieldName</th>
                <th>Previous Value</th>
              </tr>
              <xsl:for-each select="./EventData[1]/Field[(@Changed = 'false') and (string-length(./@DisplayName) &gt; 0)]">
                    <tr>
                      <th>
                        <xsl:value-of select="@DisplayName"/>
                      </th>
                      <th>
                        <xsl:value-of select="@Value"/>
                      </th>
                    </tr>
              </xsl:for-each>
            </table>
            <p>You have the prermissions to approve or reject these chanegs</p>
            <table>
              <tr>
                <td>Approve these changes</td>
                <td>Reject these changes</td>
              </tr>
              <tr>
                <td>
                  <a href="approvewithoutcomments" class="approveActionLink">
                    <input type="button" value="Approve"/>
                  </a>
                </td>
                <td>
                  <a href="approvewithoutcomments" class="approveActionLink">
                    <input type="button" value="Reject"/>
                  </a>
                </td>
              </tr>
              <tr>
                <td>
                  <a href="approvewithoutcomments" class="approveActionLink">
                    <input type="button" value="Approve with comments"/>
                  </a>
                </td>
                <td>
                  <a href="approvewithoutcomments" class="approveActionLink">
                    <input type="button" value="Reject with comments"/>
                  </a>
                </td>
              </tr>
            </table>
          </div>
          <div class="footer">
            <span>
              generated by SharePointEmails,  <xsl:value-of select="user:GetDate('dddd, dd MMMM yyyy')" />
            </span>
          </div>
        </Body>
      </Html>
    </xsl:template>
  <msxsl:script language="C#" implements-prefix="user">
    <msxsl:assembly name="System" />
    <msxsl:using namespace="System" /><![CDATA[public string GetDate(string DateFormat){return DateTime.Now.ToString(DateFormat);}]]>
  </msxsl:script>
  <xsl:template name="eventType">
    <xsl:choose>
      <xsl:when test="EventData[0]/@EventType = 1">added</xsl:when>
      <xsl:when test="EventData[0]/@EventType = 2">modified</xsl:when>
      <xsl:when test="EventData[0]/@EventType = 4">deleted</xsl:when>
      <xsl:otherwise>changed</xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <xsl:template name="itemType">
      <xsl:choose>
        <xsl:when test="a = b">item</xsl:when>
        <xsl:when test="a = b">file</xsl:when>
        <xsl:otherwise>item(file)</xsl:otherwise>
      </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
