//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointEmails.Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePointEmails.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Fields&gt;
        /// &lt;Field Name=&quot;ContentTypeId&quot; Type=&quot;string&quot; Hidden=&quot;true&quot; DisplayName=&quot;Content Type ID&quot; New=&quot;0x010100ACE5C8B4725EF143A968E58355698311&quot; /&gt;
        /// &lt;Field Name=&quot;Author&quot; Type=&quot;user&quot; DisplayName=&quot;Created By&quot; New=&quot;1&quot; LookupNewF=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;Editor&quot; Type=&quot;user&quot; DisplayName=&quot;Modified By&quot; New=&quot;1&quot; LookupNewF=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;Modified_x0020_By&quot; Type=&quot;string&quot; Hidden=&quot;true&quot; DisplayName=&quot;Document Modified By&quot; New=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;Created_x0020_By&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventDataFileAdded {
            get {
                return ResourceManager.GetString("EventDataFileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Fields&gt;
        /// &lt;Field Name=&quot;ID&quot; Type=&quot;integer&quot; Old=&quot;5&quot; /&gt;
        /// &lt;Field Name=&quot;ContentTypeId&quot; Type=&quot;unknown&quot; Hidden=&quot;true&quot; DisplayName=&quot;Content Type ID&quot; Old=&quot;0x0108009DD1F6898AFC084CB7DE58BC502A3E3D&quot; /&gt;
        /// &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; Old=&quot;title1111&quot; New=&quot;title2&quot; /&gt;
        /// &lt;Field Name=&quot;Author&quot; Type=&quot;user&quot; DisplayName=&quot;Created By&quot; Old=&quot;1&quot; LookupOldF=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;Editor&quot; Type=&quot;user&quot; DisplayName=&quot;Modified By&quot; Old=&quot;1&quot; LookupOldF=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;owshiddenversion&quot; Type=&quot;integer&quot; Hi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventDataTaskEdited_OnlyTitle {
            get {
                return ResourceManager.GetString("EventDataTaskEdited_OnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Fields&gt;
        /// &lt;Field Name=&quot;ID&quot; Type=&quot;null&quot; New=&quot;&quot; /&gt;
        /// &lt;Field Name=&quot;ContentTypeId&quot; Type=&quot;string&quot; Hidden=&quot;true&quot; DisplayName=&quot;Content Type ID&quot; New=&quot;0x0108009DD1F6898AFC084CB7DE58BC502A3E3D&quot; /&gt;
        /// &lt;Field Name=&quot;Title&quot; Type=&quot;string&quot; New=&quot;title3&quot; /&gt;
        /// &lt;Field Name=&quot;Author&quot; Type=&quot;user&quot; DisplayName=&quot;Created By&quot; New=&quot;1&quot; LookupNewF=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;Editor&quot; Type=&quot;user&quot; DisplayName=&quot;Modified By&quot; New=&quot;1&quot; LookupNewF=&quot;TEST\administrator&quot; /&gt;
        /// &lt;Field Name=&quot;GUID&quot; Type=&quot;string&quot; Hidden=&quot;true&quot; New=&quot;7C7277D4-B3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventDataTskAdded {
            get {
                return ResourceManager.GetString("EventDataTskAdded", resourceCulture);
            }
        }
    }
}
