//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharepointEmails.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharepointEmails.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; version=&apos;1.0&apos;&gt;
        ///  &lt;xsl:template match=&apos;Data&apos;&gt;
        ///    Subject for alert {SList.Title}
        ///  &lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        public static string subjXslt {
            get {
                return ResourceManager.GetString("subjXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; version=&apos;1.0&apos;&gt;
        ///  &lt;xsl:template match=&apos;Data&apos;&gt;
        ///    &lt;HTML&gt;
        ///      &lt;BODY&gt;
        ///        &lt;TABLE BORDER=&apos;2&apos;&gt;
        ///          &lt;TR&gt;
        ///            &lt;TD&gt;Field Name&lt;/TD&gt;
        ///            &lt;TD&gt;Old Value&lt;/TD&gt;
        ///            &lt;TD&gt;New Value&lt;/TD&gt;
        ///          &lt;/TR&gt;
        ///          &lt;xsl:apply-templates select=&apos;EventData&apos;/&gt;
        ///        &lt;/TABLE&gt;
        ///      &lt;/BODY&gt;
        ///    &lt;/HTML&gt;
        ///  &lt;/xsl:template&gt;
        ///  &lt;xsl:template match=&apos;EventData&apos;&gt;
        ///    &lt;xsl:apply-templates select=&apos;Field&apos;/&gt;
        ///  &lt;/xsl:template&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testbody {
            get {
                return ResourceManager.GetString("testbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Data&gt;
        ///  &lt;EventData EventType=&quot;2&quot; EventTypeName=&quot;Modify&quot;&gt;
        ///    &lt;Field Type=&quot;Type1&quot; DisplayName=&quot;Title&quot; Name=&quot;_Title&quot; Changed=&quot;false&quot; New=&quot;new value of Title&quot; Old=&quot;old value of Title&quot; Value=&quot;some value of Title&quot; /&gt;
        ///    &lt;Field Type=&quot;Type2&quot; DisplayName=&quot;FileName&quot; Name=&quot;_FileName&quot; Changed=&quot;true&quot; New=&quot;new value of FileName&quot; Old=&quot;old value of FileName&quot; Value=&quot;some value of FileName&quot; /&gt;
        ///    &lt;Field Type=&quot;Type3&quot; DisplayName=&quot;YesNoField&quot; Name=&quot;_YesNoField&quot; Changed=&quot;false&quot; N [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestContextXML {
            get {
                return ResourceManager.GetString("TestContextXML", resourceCulture);
            }
        }
    }
}
